spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.baselineOnMigrate = true

mqtt.server.port=1884
mqtt.server.max-message-size=8092
mqtt.server.backlog=128

http.server.port=8083
http.server.max-content-length=10485760
http.server.backlog=128

server.port=8091

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=Safari

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.hikari.maxLifetime=1800000
spring.datasource.hikari.validationTimeout=5000

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoints.web.base-path=/actuator
management.metrics.enable.all=true
management.metrics.web.server.auto-time-requests=true
management.metrics.binders.netty.enabled=true

topic-to-send-telemetry=telemetry-topic
topic-to-send-notification=notification-topic
spring.kafka.bootstrap-servers: localhost:29093