bot.token=7614249328:AAF6MqQGmFFP489uv4nF6nwHsxz4gTObouQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.baselineOnMigrate = true

server.port=8091

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=123

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
