name: Java CI with Maven

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5433:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Safari
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Install PostgreSQL client
        run: sudo apt-get install postgresql-client
    
      - name: List running containers
        run: docker ps

      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -h localhost -p 5433 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
      
      - name: Build with Maven
        env:
          DATABASE_URL: jdbc:postgresql://localhost:5433/postgres
        run: mvn verify
